### ISSUE TITLE
Create efficient local (on device) storage system for sensor data

### ISSUE THREAD

**Issue by jalexvig** [jalexvig/sensorship#3]
See @jdoncarlos excel sheet for calculation of amount of data that should be batched.

**Comment by jdoncarlos** [comment]
Add sensor data to the watch queue?  or does this refer to the google drive storage?

**Comment by jalexvig** [comment]
@jdoncarlos good point - clarified in the issue title

**Comment by jalexvig** [comment]
@jdoncarlos we might want to consider the CBOR data format so we don't have to manually serialize/deserialize. See https://dev.fitbit.com/build/guides/file-system/

Then if we hit data size issues we can switch to binary data.

**Comment by jdoncarlos** [comment]
Yes, sensor values can probably be represented in 2 bytes.   CBOR sounds like it will take care of the formatting.
